import Head from 'next/head';
import styles from '../styles/Home.module.css';
import NavigationBar from '../src/component/NavigationBar/navigationBar';
import FirstContent from '../src/component/FirstContent/firstContent';
import About from '../src/component/About/about';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Aziz Catfish</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavigationBar />

      <div className={styles.frontContainer}>
        <div className={styles.frontContainerMask}>
          <main className={styles.main}>
            {/* <h1 className={styles.title}>
              Welcome to <a href="https://nextjs.org">Next.js!</a>
            </h1> */}
            <FirstContent />
          </main>
        </div>
      </div>

      <section id="section-about" className={styles.aboutContainer}>
        <div className={styles.aboutContainerMask}>
          <main className={styles.main}>
            <About />
          </main>
        </div>
      </section>

      <footer className={styles.footer}>
        <a href="/" className="font-light">
          Powered by
          <span className="font-bold pl-1">
            {/* <Image src="/logo.gif" alt="Vercel Logo" width={30} height={30} /> */}
            azizCatfish
          </span>
        </a>
      </footer>
    </div>
  );
}
